### ISSUE TITLE
Request for Individual Document-aligned Corpora

### ISSUE THREAD

**Issue by GokulNC** [csebuetnlp/banglanmt#1]
Hello,

Would it be possible to upload individual datasets too in addition to the full concatenated dataset?
It would really be helpful if each (sentence-level) document-aligned corpora from your paper are uploaded individually.

Thanks a lot!

**Comment by csebuetnlp** [comment]
Due to some copyright issues, we cannot release the document-level alignments. We're considering about releasing the source-level alignments. If there's no copyright infringement, we'll be releasing them shortly.
