### ISSUE TITLE
Models checkpoints can't be accessed 

### ISSUE THREAD

**Issue by secrakib** [csebuetnlp/banglanmt#11]
![Screenshot_20241023-122140.jpg](https://github.com/user-attachments/assets/74ba57e5-80f3-48c4-a93b-5151cec553bd)

@abhik1505040

**Comment by abhik1505040** [comment]
Hi @secrakib, 

Thank you for pointing out the broken Orangedox service. We have updated the README with the corresponding Google Drive links.
