### ISSUE TITLE
Requesting for the pretrained model

### ISSUE THREAD

**Issue by Nakkhatra** [csebuetnlp/banglanmt#2]
Hi,

I was wondering if it would be possible to provide the pretrained model addressed as "bn2en_step_111000-130000-20.pt".  It would greatly help me to further progress on a project that I am working on that involves attention relation along with named entity recognition.
I am asking for the model as I don't have enough resources to train the model from scratch sadly.

Thank You
Best Regards.

**Comment by Tahmid04** [comment]
Hi, thanks for your interest in our work. We have plans to release the models in future. Please stay tuned, we will keep you updated.
