### ISSUE TITLE
How to use Pretrained Models?

### ISSUE THREAD

**Issue by MusfiqDehan** [csebuetnlp/banglanmt#3]
Hi,
How can I will be able to use your pretrained `Bengali to English` and `English to Bengali` model for machine translation? Is there any documentation available for this? I didn't find any. If any documentation available, can you refer to me please?

**Comment by abhik1505040** [comment]
Hi,
Please see the command at the bottom of [this](https://github.com/csebuetnlp/banglanmt/tree/master/training) page to evaluate these models on new texts. Make sure you maintain the required directory structure mentioned on this page.
