### ISSUE TITLE
Request to create a pypi package

### ISSUE THREAD

**Issue by mnansary** [csebuetnlp/banglanmt#5]
First of all, I must thank you for your brilliant work. I would request you package this work for easier use by the researchers. People have in fact built upon this work and are being benefitted.  As can be seen from this Facebook post: https://www.facebook.com/sawradip/posts/pfbid032jqYfjmMkRkoQvmvPFosGmU2JPa9Cfic2xn3GSkEt2LiWckHsuGAJZm6Jd36SPt6l
a Bangla 2 English adaption has  been built here: https://github.com/sawradip/Bang2Eng 
Another adaptation for English to Bangla Has been modified upon the work here:
https://colab.research.google.com/drive/1YTvocDTehO4JVB26uQe0KntMaeqsDGMt?usp=sharing
by https://github.com/mobassir94 
If you could package the work and release it under your organization (with both bn2en and en2bn) people will be much benefitted

**Comment by sawradip** [comment]
Yes...I will package this work..I plan to add some additional features. 

Currently I plan to create a package for simple translation. Would you like to propose some more features/ improvements to be added, that will be useful for users? ( As you have already seen what it currently does.)
