### ISSUE TITLE
How to use your repo for translatting an engliash csv file?

### ISSUE THREAD

**Issue by marufmoinuddin** [csebuetnlp/banglanmt#7]
I cannot figure out how I can implement this to translate a csv file. Can you please provide further instructions?

**Comment by abhik1505040** [comment]
We only support text files with one sentence per line as valid input files. To translate a CSV file, you need to convert it accordingly and use the command mentioned [here](https://github.com/csebuetnlp/banglanmt/tree/master/training#evaluation). 

Alternatively, if this process seems complicated, you can also use the [English->Bengali fine-tuned model](https://huggingface.co/csebuetnlp/banglat5_nmt_en_bn) from our other work [BanglaNLG](https://github.com/csebuetnlp/BanglaNLG) to translate your file. The corresponding APIs should be easier to use.
