### ISSUE TITLE
Missing encoder?

### ISSUE THREAD

**Issue by Mahpara** [csebuetnlp/banglanmt#9]
Hello @csebuetnlp,

I am doing my Master thesis and was trying to run your code using

``
 python pipeline.py --src_lang bn --tgt_lang en -i ../../inputFolder -o outputFolder/ --model_prefix bn2en --do_train --do_eval
``
I have the input folder in another location so I modified the command accordingly. Unfortunately I  am observing
``
sh: spm_export_vocab: command not found
``
and
``
sh: spm_encode: command not found
``
error. 

Do you have any idea where the mistake might be?

**Comment by Tahmid04** [comment]
Hi,

Thanks for using our codebase for your thesis work. Please have a look at [this issue](https://github.com/csebuetnlp/banglanmt/issues/8), It seems that the errors are similar.

**Comment by abhik1505040** [comment]
@Mahpara Please have a look at this [colab notebook](https://colab.research.google.com/drive/1r_7fTiTPlveSetUmJ645nfInEyeaLTmL?usp=sharing) to see how you can run translation on a sample file.

**Comment by farigys** [comment]
Hi, the colab notebook is not available anymore.

**Comment by Tahmid04** [comment]
The notebook hyperlink has been updated, please have a look now.

**Comment by farigys** [comment]
The issue still persists for some reason. pipeline.py cannot seem to find merged.tgt file. Here is a screenshot:

Thanks a bunch!
<img width="1647" alt="image" src="https://user-images.githubusercontent.com/8809298/230065185-5bc4bbc6-aff2-4f4a-ba1b-ffaabb1ea9db.png">

**Comment by Tahmid04** [comment]
Our repository requires a specific version of SentencePiece to be installed. Please see the notebook file for dependency and installation details.

**Comment by Tahmid04** [comment]
It is most likely due to an incompatible version of SPM installation.
Please try with the version used in the colab notebook and see if it works.



Tahmid Hasan
Assistant Professor
Department of Computer Science and Engineering
Bangladesh University of Engineering and Technology (BUET)
